/* GENERATED by tools/gen-board-map.mjs from calculations/mcu-ballmap.json (rev A.12) — do not edit.
 * Package: 289-MAPBGA (17 x 17, rows A-H J-N P R T U). 63 signal balls. MSCR index = port*32 + pin (PTA0 = 0 … PTH = 224).
 * ADC channel: sub 'P' = precision input n, 'S' = standard input n (RTD channel index: see
 * s32k396_adc.c, S32K3_ADC_CH()). */
#ifndef BOARD_PINS_H
#define BOARD_PINS_H

#include <stdint.h>

typedef enum { BP_GPIO = 0, BP_ADC, BP_SDADC, BP_PWM, BP_PWM_FAULT, BP_CAN, BP_LPSPI, BP_EIRQ, BP_FCCU, BP_SWG, BP_SYS } bp_kind_t;

typedef struct {
    const char *ball;
    const char *port;
    const char *fn;
    const char *net;
    bp_kind_t kind;
    uint8_t inst;
    uint8_t chan;
    char sub;
    uint16_t mscr;
} bp_entry_t;

#define BOARD_PIN_COUNT 63u

#define BOARD_PINS_INIT { \
    {"A2", "PTA8", "ADC3_P1", "ISNS_U", BP_ADC, 3u, 1u, 'P', 8u}, /* phase current U */ \
    {"A3", "PTA5", "RESET_b", "RESET_B", BP_SYS, 0u, 0u, '-', 5u}, /* reset */ \
    {"A5", "PTE1", "ADC1_P6", "VDC2_SE", BP_ADC, 1u, 6u, 'P', 129u}, /* V_DC channel 2 (was PTB0: no ADC) */ \
    {"A8", "SWG1_0", "SWG1_0", "SWG1", BP_SWG, 1u, 0u, 'W', 65535u}, /* resolver excitation source */ \
    {"A11", "PTA15", "ADC3_P4", "MT1_SIG", BP_ADC, 3u, 4u, 'P', 15u}, /* motor temp 1 (PTA12 absent) */ \
    {"A12", "PTA16", "SDADC1_AN[0]", "VREXM_P", BP_SDADC, 1u, 0u, 'N', 16u}, /* excitation monitor + (SDADC1 AN0) */ \
    {"A13", "PTA0", "ADC6_P4", "VDC1_SE", BP_ADC, 6u, 4u, 'P', 0u}, /* V_DC channel 1 */ \
    {"A14", "PTB8", "ADC4_P5", "ISNS_V", BP_ADC, 4u, 5u, 'P', 40u}, /* phase current V */ \
    {"A15", "PTD27", "ADC4_P6", "V5GD_SNS", BP_ADC, 4u, 6u, 'P', 123u}, /* V5GD/2 monitor (was PTB5: no ADC) */ \
    {"A16", "PTD26", "SDADC2_AN[1]", "SIN_N", BP_SDADC, 2u, 1u, 'N', 122u}, /* resolver SIN- (SDADC2 AN1) */ \
    {"B3", "PTA9", "ADC0_P7", "TMOD_U", BP_ADC, 0u, 7u, 'P', 9u}, /* module NTC U */ \
    {"B4", "PTE31", "", "INTRLOK_P", BP_GPIO, 0u, 0u, 'G', 159u}, /* HVIL ladder drive */ \
    {"B10", "PTE2", "ADC3_P2", "TMOD_V", BP_ADC, 3u, 2u, 'P', 130u}, /* module NTC V (was PTB2: mux-address output) */ \
    {"B11", "PTE6", "ADC3_P3", "NTC_H", BP_ADC, 3u, 3u, 'P', 134u}, /* board NTC hot zone (PTA11 absent on this package) */ \
    {"B12", "PTC7", "EIRQ[7]", "SBC_INTB", BP_EIRQ, 0u, 7u, 'E', 71u}, /* FS26 INTB (EIRQ) */ \
    {"B13", "PTD28", "SDADC3_AN[0]", "COS_P", BP_SDADC, 3u, 0u, 'N', 124u}, /* resolver COS+ (SDADC3 AN0) */ \
    {"B14", "PTA1", "SDADC3_AN[1]", "COS_N", BP_SDADC, 3u, 1u, 'N', 1u}, /* resolver COS- (SDADC3 AN1) */ \
    {"C2", "PTE16", "FCCU_ERR1", "FCCU_ERR1", BP_FCCU, 0u, 1u, 'F', 144u}, /* FCCU error out 1 */ \
    {"C3", "PTA22", "CAN1_RX", "CAN1_RX", BP_CAN, 1u, 1u, 'C', 22u}, /* FlexCAN1 RX */ \
    {"C12", "PTC6", "ADC3_P6", "HW_ID", BP_ADC, 3u, 6u, 'P', 70u}, /* SKU identity (was PTB4: no ADC) */ \
    {"C13", "PTD31", "", "MCU_EN_FLYBK_LS", BP_GPIO, 0u, 0u, 'G', 127u}, /* flyback LS enable (OR) */ \
    {"C14", "PTD29", "ADC5_P7", "NTC_A", BP_ADC, 5u, 7u, 'P', 125u}, /* board NTC ambient (was PTA10 = JTAG_TDO) */ \
    {"C15", "PTB9", "SDADC2_AN[0]", "SIN_P", BP_SDADC, 2u, 0u, 'N', 41u}, /* resolver SIN+ (SDADC2 AN0) */ \
    {"C17", "PTB11", "ADC0_S14", "SBC_AMUX", BP_ADC, 0u, 14u, 'S', 43u}, /* FS26 AMUX (was a named ADC0_S12 pin) */ \
    {"D2", "PTE15", "FCCU_ERR0", "FCCU_ERR0", BP_FCCU, 0u, 0u, 'F', 143u}, /* FCCU error out 0 */ \
    {"D3", "PTA23", "CAN1_TX", "CAN1_TX", BP_CAN, 1u, 0u, 'C', 23u}, /* FlexCAN1 TX */ \
    {"D8", "PTE23", "ADC1_P7", "INTRLOK_N", BP_ADC, 1u, 7u, 'P', 151u}, /* HVIL signature (was PTF5: no ADC) */ \
    {"D11", "PTE18", "ADC3_P5", "MT2_SIG", BP_ADC, 3u, 5u, 'P', 146u}, /* motor temp 2 (PTA13 absent) */ \
    {"D12", "PTE17", "SDADC1_AN[1]", "VREXM_N", BP_SDADC, 1u, 1u, 'N', 145u}, /* excitation monitor - (SDADC1 AN1) */ \
    {"D13", "PTD30", "", "MCU_EN_FLYBK_HS", BP_GPIO, 0u, 0u, 'G', 126u}, /* flyback HS enable (OR) */ \
    {"D15", "PTB10", "EIRQ[24]", "RDY_HS", BP_EIRQ, 0u, 24u, 'E', 42u}, /* RDY HS bank (GPIO/EIRQ) */ \
    {"F2", "PTE5", "ADC1_S8", "TMOD_W", BP_ADC, 1u, 8u, 'S', 133u}, /* module NTC W (was PTB3: mux-address output) */ \
    {"F6", "PTA4", "JTAG_TMS", "TMS", BP_SYS, 0u, 0u, '-', 4u}, /* JTAG TMS / SWDIO */ \
    {"F7", "PTC4", "JTAG_TCK", "TCK", BP_SYS, 0u, 0u, '-', 68u}, /* JTAG TCK / SWCLK */ \
    {"F8", "PTC5", "JTAG_TDI", "TDI", BP_SYS, 0u, 0u, '-', 69u}, /* JTAG TDI */ \
    {"G8", "PTA10", "JTAG_TDO", "TDO", BP_SYS, 0u, 0u, '-', 10u}, /* JTAG TDO / SWO */ \
    {"G15", "PTF16", "LPSPI3_PCS0", "SBC_CS", BP_LPSPI, 3u, 3u, 'S', 176u}, /* LPSPI3 PCS0 */ \
    {"H1", "PTA25", "ADC0_S8", "IGN_SNS", BP_ADC, 0u, 8u, 'S', 25u}, /* KL15 sense */ \
    {"H16", "PTB13", "ADC0_S19", "ISNS_W", BP_ADC, 0u, 19u, 'S', 45u}, /* phase current W */ \
    {"K1", "EXTAL", "", "EXTAL", BP_GPIO, 0u, 0u, 'G', 65535u}, /* 40 MHz crystal */ \
    {"K15", "PTD20", "LPSPI3_SIN", "SBC_MISO", BP_LPSPI, 3u, 1u, 'S', 116u}, /* LPSPI3 SIN */ \
    {"L1", "XTAL", "", "XTAL", BP_GPIO, 0u, 0u, 'G', 65535u}, /* 40 MHz crystal */ \
    {"L14", "PTC31", "PWM_1_A[0]", "PWM_UH", BP_PWM, 1u, 0u, 'A', 95u}, /* PWM U high */ \
    {"L17", "PTA17", "LPSPI3_SOUT", "SBC_MOSI", BP_LPSPI, 3u, 0u, 'S', 17u}, /* LPSPI3 SOUT */ \
    {"M15", "PTA6", "PWM_1_B[0]", "PWM_UL", BP_PWM, 1u, 0u, 'B', 6u}, /* PWM U low */ \
    {"M16", "PTA7", "PWM_1_B[1]", "PWM_VL", BP_PWM, 1u, 1u, 'B', 7u}, /* PWM V low */ \
    {"M17", "PTE7", "LPSPI3_SCK", "SBC_SCK", BP_LPSPI, 3u, 2u, 'S', 135u}, /* LPSPI3 SCK */ \
    {"N15", "PTC8", "PWM_1_B[2]", "PWM_WL", BP_PWM, 1u, 2u, 'B', 72u}, /* PWM W low */ \
    {"N16", "PTC29", "PWM_1_A[2]", "PWM_WH", BP_PWM, 1u, 2u, 'A', 93u}, /* PWM W high */ \
    {"N17", "PTC30", "PWM_1_A[1]", "PWM_VH", BP_PWM, 1u, 1u, 'A', 94u}, /* PWM V high */ \
    {"P2", "PTD16", "", "MCU_GATE_EN", BP_GPIO, 0u, 0u, 'G', 112u}, /* gate enable (UAND1.B) */ \
    {"P15", "PTC26", "PWM_1_FAULT[0]", "FLT_HS_N", BP_PWM_FAULT, 1u, 0u, 'F', 90u}, /* driver fault HS bank -> eFlexPWM1 FAULT0 (hardware PWM inhibit, FW-15) */ \
    {"R8", "PTD8", "", "ASC_CLR_M", BP_GPIO, 0u, 0u, 'G', 104u}, /* ASC clear */ \
    {"R13", "PTC21", "CAN0_TX", "CAN0_TX", BP_CAN, 0u, 0u, 'C', 85u}, /* FlexCAN0 TX (GEN3 choice) */ \
    {"R14", "PTC25", "PWM_1_FAULT[2]", "FLT_LS_N", BP_PWM_FAULT, 1u, 2u, 'F', 89u}, /* driver fault LS bank -> eFlexPWM1 FAULT2 */ \
    {"R17", "PTB1", "ADC4_S11", "VOFS", BP_ADC, 4u, 11u, 'S', 33u}, /* receiver offset monitor */ \
    {"T5", "PTD6", "", "ASC_REQ", BP_GPIO, 0u, 0u, 'G', 102u}, /* ASC request (latch clock) */ \
    {"T6", "PTD10", "", "DRV_EN_RB", BP_GPIO, 0u, 0u, 'G', 106u}, /* DRV_EN read-back */ \
    {"U2", "PTB5", "EIRQ[13]", "RDY_LS", BP_EIRQ, 0u, 13u, 'E', 37u}, /* RDY LS bank (GPIO/EIRQ) */ \
    {"U5", "PTD5", "", "QDIS_M", BP_GPIO, 0u, 0u, 'G', 101u}, /* discharge command */ \
    {"U6", "PTD11", "", "ASC_CMD_RB", BP_GPIO, 0u, 0u, 'G', 107u}, /* ASC_CMD read-back */ \
    {"U8", "PTD9", "", "FLT_CLR_M", BP_GPIO, 0u, 0u, 'G', 105u}, /* fault-latch clear one-shot */ \
    {"U14", "PTC23", "CAN0_RX", "CAN0_RX", BP_CAN, 0u, 1u, 'C', 87u}, /* FlexCAN0 RX (GEN3 choice) */ \
}

#define BP_ISNS_U_MSCR 8u
#define BP_ISNS_U_INST 3u
#define BP_ISNS_U_CHAN 1u
#define BP_RESET_B_MSCR 5u
#define BP_VDC2_SE_MSCR 129u
#define BP_VDC2_SE_INST 1u
#define BP_VDC2_SE_CHAN 6u
#define BP_SWG1_MSCR 65535u
#define BP_SWG1_INST 1u
#define BP_SWG1_CHAN 0u
#define BP_MT1_SIG_MSCR 15u
#define BP_MT1_SIG_INST 3u
#define BP_MT1_SIG_CHAN 4u
#define BP_VREXM_P_MSCR 16u
#define BP_VREXM_P_INST 1u
#define BP_VREXM_P_CHAN 0u
#define BP_VDC1_SE_MSCR 0u
#define BP_VDC1_SE_INST 6u
#define BP_VDC1_SE_CHAN 4u
#define BP_ISNS_V_MSCR 40u
#define BP_ISNS_V_INST 4u
#define BP_ISNS_V_CHAN 5u
#define BP_V5GD_SNS_MSCR 123u
#define BP_V5GD_SNS_INST 4u
#define BP_V5GD_SNS_CHAN 6u
#define BP_SIN_N_MSCR 122u
#define BP_SIN_N_INST 2u
#define BP_SIN_N_CHAN 1u
#define BP_TMOD_U_MSCR 9u
#define BP_TMOD_U_INST 0u
#define BP_TMOD_U_CHAN 7u
#define BP_INTRLOK_P_MSCR 159u
#define BP_TMOD_V_MSCR 130u
#define BP_TMOD_V_INST 3u
#define BP_TMOD_V_CHAN 2u
#define BP_NTC_H_MSCR 134u
#define BP_NTC_H_INST 3u
#define BP_NTC_H_CHAN 3u
#define BP_SBC_INTB_MSCR 71u
#define BP_SBC_INTB_INST 0u
#define BP_SBC_INTB_CHAN 7u
#define BP_COS_P_MSCR 124u
#define BP_COS_P_INST 3u
#define BP_COS_P_CHAN 0u
#define BP_COS_N_MSCR 1u
#define BP_COS_N_INST 3u
#define BP_COS_N_CHAN 1u
#define BP_FCCU_ERR1_MSCR 144u
#define BP_FCCU_ERR1_INST 0u
#define BP_FCCU_ERR1_CHAN 1u
#define BP_CAN1_RX_MSCR 22u
#define BP_CAN1_RX_INST 1u
#define BP_CAN1_RX_CHAN 1u
#define BP_HW_ID_MSCR 70u
#define BP_HW_ID_INST 3u
#define BP_HW_ID_CHAN 6u
#define BP_MCU_EN_FLYBK_LS_MSCR 127u
#define BP_NTC_A_MSCR 125u
#define BP_NTC_A_INST 5u
#define BP_NTC_A_CHAN 7u
#define BP_SIN_P_MSCR 41u
#define BP_SIN_P_INST 2u
#define BP_SIN_P_CHAN 0u
#define BP_SBC_AMUX_MSCR 43u
#define BP_SBC_AMUX_INST 0u
#define BP_SBC_AMUX_CHAN 14u
#define BP_FCCU_ERR0_MSCR 143u
#define BP_FCCU_ERR0_INST 0u
#define BP_FCCU_ERR0_CHAN 0u
#define BP_CAN1_TX_MSCR 23u
#define BP_CAN1_TX_INST 1u
#define BP_CAN1_TX_CHAN 0u
#define BP_INTRLOK_N_MSCR 151u
#define BP_INTRLOK_N_INST 1u
#define BP_INTRLOK_N_CHAN 7u
#define BP_MT2_SIG_MSCR 146u
#define BP_MT2_SIG_INST 3u
#define BP_MT2_SIG_CHAN 5u
#define BP_VREXM_N_MSCR 145u
#define BP_VREXM_N_INST 1u
#define BP_VREXM_N_CHAN 1u
#define BP_MCU_EN_FLYBK_HS_MSCR 126u
#define BP_RDY_HS_MSCR 42u
#define BP_RDY_HS_INST 0u
#define BP_RDY_HS_CHAN 24u
#define BP_TMOD_W_MSCR 133u
#define BP_TMOD_W_INST 1u
#define BP_TMOD_W_CHAN 8u
#define BP_TMS_MSCR 4u
#define BP_TCK_MSCR 68u
#define BP_TDI_MSCR 69u
#define BP_TDO_MSCR 10u
#define BP_SBC_CS_MSCR 176u
#define BP_SBC_CS_INST 3u
#define BP_SBC_CS_CHAN 3u
#define BP_IGN_SNS_MSCR 25u
#define BP_IGN_SNS_INST 0u
#define BP_IGN_SNS_CHAN 8u
#define BP_ISNS_W_MSCR 45u
#define BP_ISNS_W_INST 0u
#define BP_ISNS_W_CHAN 19u
#define BP_EXTAL_MSCR 65535u
#define BP_SBC_MISO_MSCR 116u
#define BP_SBC_MISO_INST 3u
#define BP_SBC_MISO_CHAN 1u
#define BP_XTAL_MSCR 65535u
#define BP_PWM_UH_MSCR 95u
#define BP_PWM_UH_INST 1u
#define BP_PWM_UH_CHAN 0u
#define BP_SBC_MOSI_MSCR 17u
#define BP_SBC_MOSI_INST 3u
#define BP_SBC_MOSI_CHAN 0u
#define BP_PWM_UL_MSCR 6u
#define BP_PWM_UL_INST 1u
#define BP_PWM_UL_CHAN 0u
#define BP_PWM_VL_MSCR 7u
#define BP_PWM_VL_INST 1u
#define BP_PWM_VL_CHAN 1u
#define BP_SBC_SCK_MSCR 135u
#define BP_SBC_SCK_INST 3u
#define BP_SBC_SCK_CHAN 2u
#define BP_PWM_WL_MSCR 72u
#define BP_PWM_WL_INST 1u
#define BP_PWM_WL_CHAN 2u
#define BP_PWM_WH_MSCR 93u
#define BP_PWM_WH_INST 1u
#define BP_PWM_WH_CHAN 2u
#define BP_PWM_VH_MSCR 94u
#define BP_PWM_VH_INST 1u
#define BP_PWM_VH_CHAN 1u
#define BP_MCU_GATE_EN_MSCR 112u
#define BP_FLT_HS_N_MSCR 90u
#define BP_FLT_HS_N_INST 1u
#define BP_FLT_HS_N_CHAN 0u
#define BP_ASC_CLR_M_MSCR 104u
#define BP_CAN0_TX_MSCR 85u
#define BP_CAN0_TX_INST 0u
#define BP_CAN0_TX_CHAN 0u
#define BP_FLT_LS_N_MSCR 89u
#define BP_FLT_LS_N_INST 1u
#define BP_FLT_LS_N_CHAN 2u
#define BP_VOFS_MSCR 33u
#define BP_VOFS_INST 4u
#define BP_VOFS_CHAN 11u
#define BP_ASC_REQ_MSCR 102u
#define BP_DRV_EN_RB_MSCR 106u
#define BP_RDY_LS_MSCR 37u
#define BP_RDY_LS_INST 0u
#define BP_RDY_LS_CHAN 13u
#define BP_QDIS_M_MSCR 101u
#define BP_ASC_CMD_RB_MSCR 107u
#define BP_FLT_CLR_M_MSCR 105u
#define BP_CAN0_RX_MSCR 87u
#define BP_CAN0_RX_INST 0u
#define BP_CAN0_RX_CHAN 1u

#endif /* BOARD_PINS_H */
