#!/usr/bin/env node
// licences.mjs — the two LGPL release items of NOTICES.md, done by machine so a package can never ship without them.
//
//   node scripts/licences.mjs sources [--out <dir>]   corresponding source: the exact Qt submodule and Qwt archives Homebrew
//                                                     built the bundled frameworks from (url + sha256 read from the installed
//                                                     formulae, downloaded once into build/corresponding-source/, verified),
//                                                     the formula files (the build recipes), a MANIFEST.md, and the Qt
//                                                     third-party attributions (every qt_attribution.json of those modules,
//                                                     with their licence texts) generated into licenses/QT-THIRD-PARTY.md +
//                                                     licenses/third-party/qt/.
//   node scripts/licences.mjs table --app <Traction Tool.app>
//                                                     regenerates the bundled-library table of NOTICES.md (between the
//                                                     markers) from what is ACTUALLY in Contents/Frameworks of the staged
//                                                     bundle, copying each library's licence text from its Homebrew keg into
//                                                     licenses/third-party/. Exits 1 on a library it cannot attribute.
// Both run from the package_dmg target (CMakeLists.txt). No network is needed after the first `sources` run.
import { execFileSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync, copyFileSync, realpathSync, statSync, rmSync } from "node:fs";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const QT = dirname(dirname(fileURLToPath(import.meta.url)));       // tool/qt
const argvOut = process.argv.indexOf("--out");                       // packaging passes the CMake binary dir
const OUT = argvOut > 0 && process.argv[argvOut + 1] ? resolve(process.argv[argvOut + 1]) : join(QT, "build", "corresponding-source");
const LIC = join(QT, "licenses");
const sh = (cmd, args, opts = {}) => execFileSync(cmd, args, { encoding: "utf8", ...opts });
const sha256 = (p) => createHash("sha256").update(readFileSync(p)).digest("hex");
const brewPrefix = (f) => sh("brew", ["--prefix", f]).trim();
const fail = (m) => { console.error(`licences: ${m}`); process.exit(1); };

// ---------------------------------------------------------------- sources ----------------------------------------------------
const MODULES = ["qtbase", "qtsvg", "qtserialbus", "qtserialport", "qwt"]; // what Contents/Frameworks carries (Qt + Qwt)

function formulaSource(name) {
  const rb = sh("brew", ["formula", name]).trim();
  const text = readFileSync(rb, "utf8");
  const url = /^\s*url\s+"([^"]+)"/m.exec(text)?.[1];
  const sha = text.slice(text.indexOf(url)).match(/sha256\s+"([0-9a-f]{64})"/)?.[1];
  if (!url || !sha) fail(`${name}: url/sha256 not found in ${rb}`);
  return { name, rb, url, sha, file: basename(url) };
}

function sources() {
  mkdirSync(OUT, { recursive: true });
  const rows = [];
  for (const m of MODULES) {
    const s = formulaSource(m);
    const dst = join(OUT, s.file);
    if (!existsSync(dst) || sha256(dst) !== s.sha) {
      console.log(`  downloading ${s.file}`);
      sh("curl", ["-fsSL", "--retry", "3", "-o", dst, s.url], { stdio: "inherit" });
      if (sha256(dst) !== s.sha) fail(`${s.file}: sha256 mismatch against the formula (${s.sha})`);
    }
    copyFileSync(s.rb, join(OUT, basename(s.rb)));
    rows.push({ ...s, size: statSync(dst).size });
    console.log(`  ${s.file}  sha256 ${s.sha.slice(0, 16)}…  ok`);
  }
  writeFileSync(join(OUT, "MANIFEST.md"), `# Traction Tool — corresponding source (LGPL-3.0 §4 d) 0 / LGPL-2.1 §6)

The dynamically linked Qt frameworks and Qwt inside "Traction Tool.app" were built by Homebrew from these unmodified upstream
archives; the .rb files beside them are the build recipes Homebrew used (compiler flags, configure options, patches). This
directory is shipped next to the application image as TractionTool-<version>-corresponding-source.zip, so no written offer
is needed. Verify: \`shasum -a 256 <file>\` against the column below.

| Archive | Bytes | sha256 | Recipe |
|---|---|---|---|
${rows.map((r) => `| ${r.file} | ${r.size} | ${r.sha} | ${basename(r.rb)} |`).join("\n")}

Generated by tool/qt/scripts/licences.mjs on ${new Date().toISOString().slice(0, 10)}.
`);
  attributions(rows.filter((r) => r.name !== "qwt"));
}

// Every qt_attribution.json of the four modules → one table + the licence texts (over-inclusion is harmless; a component
// that is only in tests/tools/examples is listed as such, not dropped, so a reader can judge).
function attributions(qtRows) {
  const work = join(OUT, "attributions");
  rmSync(work, { recursive: true, force: true });
  mkdirSync(work, { recursive: true });
  const outDir = join(LIC, "third-party", "qt");
  rmSync(outDir, { recursive: true, force: true });
  mkdirSync(outDir, { recursive: true });
  const table = [];
  for (const r of qtRows) {
    const archive = join(OUT, r.file);
    try {
      sh("tar", ["-xf", archive, "-C", work, "--include=*qt_attribution.json"], { stdio: ["ignore", "ignore", "pipe"] });
    } catch (e) { // a module with no third-party code at all (qtserialport) makes tar report "Not found in archive"
      if (!/Not found in archive/.test(String(e.stderr))) throw e;
    }
    const jsons = [];
    const walk = (d) => { for (const e of readdirSync(d, { withFileTypes: true })) { const p = join(d, e.name); if (e.isDirectory()) walk(p); else if (e.name === "qt_attribution.json") jsons.push(p); } };
    const top = readdirSync(work).find((d) => d.startsWith(r.name + "-"));
    if (!top) { console.log(`  ${r.file}: no qt_attribution.json (no third-party code)`); continue; }
    walk(join(work, top));
    // second pass: the licence files the JSONs name (members are addressed by their archive path)
    const wanted = new Map(); // archive member → { entry, json dir }
    const entries = [];
    for (const j of jsons) {
      let parsed;
      // Qt's attribution files are not always strict JSON (raw tabs/newlines inside strings): fold control characters
      try { parsed = JSON.parse(readFileSync(j, "utf8").replace(/[\x00-\x1F]/g, " ")); } catch (e) { fail(`${j}: ${e.message}`); }
      for (const e of Array.isArray(parsed) ? parsed : [parsed]) {
        let files = [].concat(e.LicenseFile ?? e.LicenseFiles ?? []).filter(Boolean);
        const relDir = dirname(j).slice(work.length + 1); // <top>/src/3rdparty/x
        if (!files.length && e.LicenseId) { // no file named: Qt keeps the SPDX texts in <top>/LICENSES/<Id>.txt
          const depth = relDir.split("/").length - 1;
          files = String(e.LicenseId).split(/\s+(?:AND|OR|WITH)\s+/i).map((id) => `${"../".repeat(depth)}LICENSES/${id.replace(/[()]/g, "")}.txt`);
        }
        entries.push({ module: r.name, e, relDir, files });
        for (const f of files) wanted.set(join(relDir, f), true);
      }
    }
    if (wanted.size) { // members that do not exist (an SPDX text Qt does not ship) only make tar complain; the row then says so
      try { sh("tar", ["-xf", archive, "-C", work, ...[...wanted.keys()]], { stdio: ["ignore", "ignore", "pipe"] }); }
      catch (e) { if (!/Not found in archive/.test(String(e.stderr))) throw e; }
    }
    for (const { module, e, relDir, files } of entries) {
      const id = String(e.Id ?? e.Name ?? "unnamed").replace(/[^A-Za-z0-9._-]+/g, "_");
      const copied = [];
      for (const f of files) {
        const src = join(work, relDir, f);
        if (!existsSync(src)) continue;
        const dst = join(outDir, `${module}-${id}-${basename(f)}`);
        copyFileSync(src, dst);
        copied.push(`third-party/qt/${basename(dst)}`);
      }
      const parts = [].concat(e.QtParts ?? ["libs"]).join(" ");
      table.push(`| ${module} | ${e.Name ?? e.Id} | ${e.Version ?? "—"} | ${e.LicenseId ?? e.License ?? "—"} | ${parts} | ${copied.join(", ") || (e.License ? "(no text file: " + e.License + ")" : "—")} |`);
    }
  }
  table.sort();
  writeFileSync(join(LIC, "QT-THIRD-PARTY.md"), `# Third-party code inside the bundled Qt modules

Generated by tool/qt/scripts/licences.mjs from the qt_attribution.json files of the exact Qt ${qtRows[0].file.match(/\d+\.\d+\.\d+/)[0]} submodule
sources the frameworks were built from (see build/corresponding-source/MANIFEST.md). Qt's own attribution files are the
authoritative list; every entry is kept, with its QtParts column (libs / tools / tests / examples) so a reader can see which
ones are inside the shipped libraries. Licence texts are in \`third-party/qt/\` (${readdirSync(outDir).length} files).

| Module | Component | Version | Licence | Qt parts | Text |
|---|---|---|---|---|---|
${table.join("\n")}
`);
  console.log(`  QT-THIRD-PARTY.md: ${table.length} attributions, ${readdirSync(outDir).length} licence files`);
}

// ---------------------------------------------------------------- table ------------------------------------------------------
// dylib basename (without version/extension) → its Homebrew formula, display name, SPDX and where its licence text lives.
// `text` names a shipped file instead of a keg copy (kegs of glib/gettext carry no LGPL text; the library licence is LGPL-2.1).
const LIBS = {
  libglib: { f: "glib", name: "GLib (`libglib`, `libgio`, `libgobject`, `libgmodule`, `libgthread`)", spdx: "LGPL-2.1-or-later", text: "LGPL-2.1.txt", group: "glib" },
  libgio: { group: "glib" }, libgobject: { group: "glib" }, libgmodule: { group: "glib" }, libgthread: { group: "glib" },
  libintl: { f: "gettext", name: "gettext runtime (`libintl`)", spdx: "LGPL-2.1-or-later (the library)", text: "LGPL-2.1.txt" },
  libdbus: { f: "dbus", name: "D-Bus (`libdbus-1`)", spdx: "AFL-2.1 OR GPL-2.0-or-later (AFL-2.1 chosen)", keg: "COPYING" },
  libicuuc: { f: "icu4c@78", name: "ICU (`libicuuc`, `libicui18n`, `libicudata`)", spdx: "Unicode-3.0", keg: "LICENSE", group: "icu" },
  libicui18n: { group: "icu" }, libicudata: { group: "icu" },
  libssl: { f: "openssl@3", name: "OpenSSL (`libssl`, `libcrypto`)", spdx: "Apache-2.0", keg: "LICENSE.txt", group: "openssl" }, libcrypto: { group: "openssl" },
  libharfbuzz: { f: "harfbuzz", name: "HarfBuzz (`libharfbuzz`)", spdx: "MIT", keg: "COPYING" },
  libfreetype: { f: "freetype", name: "FreeType (`libfreetype`)", spdx: "FTL (chosen) OR GPL-2.0", keg: "LICENSE.TXT" },
  libgraphite2: { f: "graphite2", name: "Graphite2 (`libgraphite2`)", spdx: "MIT OR MPL-2.0 OR LGPL-2.1+ OR GPL-2.0+ (MIT chosen)", keg: "LICENSE" },
  libpcre2: { f: "pcre2", name: "PCRE2 (`libpcre2-8`, `libpcre2-16`)", spdx: "BSD-3-Clause", keg: "LICENCE.md" },
  "libdouble-conversion": { f: "double-conversion", name: "double-conversion", spdx: "BSD-3-Clause", keg: "LICENSE" },
  libpng16: { f: "libpng", name: "libpng (`libpng16`)", spdx: "libpng-2.0", keg: "LICENSE" },
  libjpeg: { f: "jpeg-turbo", name: "libjpeg-turbo (`libjpeg`)", spdx: "IJG AND BSD-3-Clause AND Zlib", keg: "LICENSE.md" },
  libzstd: { f: "zstd", name: "Zstandard (`libzstd`)", spdx: "BSD-3-Clause (chosen) OR GPL-2.0", keg: "LICENSE" },
  libbrotlicommon: { f: "brotli", name: "Brotli (`libbrotlicommon`, `libbrotlidec`)", spdx: "MIT", keg: "LICENSE", group: "brotli" }, libbrotlidec: { group: "brotli" },
  libmd4c: { f: "md4c", name: "MD4C (`libmd4c`)", spdx: "MIT", keg: "LICENSE.md" },
  libb2: { f: "libb2", name: "BLAKE2 (`libb2`)", spdx: "CC0-1.0", keg: "COPYING" },
};

function table(app) {
  const fw = join(app, "Contents", "Frameworks");
  if (!existsSync(fw)) fail(`${fw} does not exist (run macdeployqt first)`);
  const dylibs = readdirSync(fw).filter((f) => f.endsWith(".dylib"));
  const frameworks = readdirSync(fw).filter((f) => f.endsWith(".framework")).map((f) => f.replace(".framework", ""));
  for (const f of frameworks) if (!/^Qt|^qwt$/.test(f)) fail(`${f}.framework is bundled but not covered by NOTICES.md`);
  const seen = new Map();
  for (const d of dylibs) {
    let key = d.replace(/\.dylib$/, "");
    while (/[-.]\d+(\.\d+)*$/.test(key)) key = key.replace(/[-.]\d+(\.\d+)*$/, ""); // libgio-2.0.0 → libgio, libssl.3 → libssl
    let e = LIBS[key];
    if (!e) fail(`${d}: no attribution entry — add it to LIBS in scripts/licences.mjs`);
    if (e.group && !e.f) e = Object.values(LIBS).find((x) => x.group === e.group && x.f);
    seen.set(e.f, e);
  }
  const tp = join(LIC, "third-party");
  mkdirSync(tp, { recursive: true });
  const rows = [];
  for (const [f, e] of [...seen].sort((a, b) => a[1].name.localeCompare(b[1].name))) {
    const keg = realpathSync(brewPrefix(f));
    const version = basename(keg).replace(/_\d+$/, "");
    let text = e.text;
    if (!text) {
      const src = join(keg, e.keg);
      if (!existsSync(src)) fail(`${f}: ${e.keg} not in ${keg}`);
      const dst = `${f.replace(/@.*$/, "")}-${basename(e.keg)}`;
      copyFileSync(src, join(tp, dst));
      text = `third-party/${dst}`;
    }
    rows.push(`| ${e.name} | ${version} | ${e.spdx} | \`${text}\` |`);
  }
  const p = join(QT, "NOTICES.md");
  const s = readFileSync(p, "utf8");
  const a = s.indexOf("<!-- bundled-libraries:begin -->"), b = s.indexOf("<!-- bundled-libraries:end -->");
  if (a < 0 || b < 0) fail("NOTICES.md markers missing");
  const block = `<!-- bundled-libraries:begin -->
| Library (files in \`Contents/Frameworks\`) | Version | Licence (SPDX) | Text |
|---|---|---|---|
${rows.join("\n")}

Table generated by \`scripts/licences.mjs table\` from the staged bundle (${dylibs.length} dylibs, ${frameworks.length} frameworks: ${frameworks.join(", ")}).
`;
  writeFileSync(p, s.slice(0, a) + block + s.slice(b));
  console.log(`  NOTICES.md: ${rows.length} bundled libraries attributed from ${dylibs.length} dylibs`);
}

const [cmd, ...rest] = process.argv.slice(2);
if (cmd === "sources") sources();
else if (cmd === "table") { const i = rest.indexOf("--app"); if (i < 0 || !rest[i + 1]) fail("table needs --app <Traction Tool.app>"); table(resolve(rest[i + 1])); }
else fail("usage: licences.mjs sources [--out <dir>] | table --app <bundle>");
