/* GENERATED by tools/gen-params.mjs — do not edit. Range of every cal_* parameter. */
#ifndef CAL_RANGES_H
#define CAL_RANGES_H

#include <stddef.h>
#include "ti_params.h"

#define TI_CAL_RANGES_INIT { \
    {"cal_vdc_disagree_floor_v", offsetof(ti_params_t, cal_vdc_disagree_floor_v), TI_CAL_F32, 5.0f, 40.0f}, \
    {"cal_vdc_stale_us", offsetof(ti_params_t, cal_vdc_stale_us), TI_CAL_U32, 20.0f, 1000.0f}, \
    {"cal_vdc_bms_debounce_ms", offsetof(ti_params_t, cal_vdc_bms_debounce_ms), TI_CAL_U32, 10.0f, 500.0f}, \
    {"cal_isum_tol_a", offsetof(ti_params_t, cal_isum_tol_a), TI_CAL_F32, 15.0f, 90.0f}, \
    {"cal_isum_debounce", offsetof(ti_params_t, cal_isum_debounce), TI_CAL_U8, 1.0f, 10.0f}, \
    {"cal_isns_offset_tol_v", offsetof(ti_params_t, cal_isns_offset_tol_v), TI_CAL_F32, 0.02f, 0.25f}, \
    {"cal_dtcomp_band_a", offsetof(ti_params_t, cal_dtcomp_band_a), TI_CAL_F32, 1.0f, 30.0f}, \
    {"cal_isns_stale_us", offsetof(ti_params_t, cal_isns_stale_us), TI_CAL_U32, 50.0f, 1000.0f}, \
    {"cal_ntc_open_v", offsetof(ti_params_t, cal_ntc_open_v), TI_CAL_F32, 4.7f, 4.98f}, \
    {"cal_ntc_short_v", offsetof(ti_params_t, cal_ntc_short_v), TI_CAL_F32, 0.02f, 0.3f}, \
    {"cal_temp_rate_c_s", offsetof(ti_params_t, cal_temp_rate_c_s), TI_CAL_F32, 5.0f, 100.0f}, \
    {"cal_tmod_derate_start_c", offsetof(ti_params_t, cal_tmod_derate_start_c), TI_CAL_F32, 60.0f, 120.0f}, \
    {"cal_tmod_derate_end_c", offsetof(ti_params_t, cal_tmod_derate_end_c), TI_CAL_F32, 80.0f, 140.0f}, \
    {"cal_derate_hyst_c", offsetof(ti_params_t, cal_derate_hyst_c), TI_CAL_F32, 1.0f, 15.0f}, \
    {"cal_coolant_derate_start_c", offsetof(ti_params_t, cal_coolant_derate_start_c), TI_CAL_F32, 50.0f, 80.0f}, \
    {"cal_coolant_derate_end_c", offsetof(ti_params_t, cal_coolant_derate_end_c), TI_CAL_F32, 60.0f, 95.0f}, \
    {"cal_peak_recovery_s", offsetof(ti_params_t, cal_peak_recovery_s), TI_CAL_F32, 60.0f, 600.0f}, \
    {"cal_ign_on_v", offsetof(ti_params_t, cal_ign_on_v), TI_CAL_F32, 4.0f, 9.0f}, \
    {"cal_ign_off_v", offsetof(ti_params_t, cal_ign_off_v), TI_CAL_F32, 2.0f, 6.0f}, \
    {"cal_ign_debounce_ms", offsetof(ti_params_t, cal_ign_debounce_ms), TI_CAL_U32, 5.0f, 100.0f}, \
    {"cal_hvil_tol_v", offsetof(ti_params_t, cal_hvil_tol_v), TI_CAL_F32, 0.1f, 0.24f}, \
    {"cal_hvil_period_ms", offsetof(ti_params_t, cal_hvil_period_ms), TI_CAL_U32, 5.0f, 25.0f}, \
    {"cal_hvil_debounce", offsetof(ti_params_t, cal_hvil_debounce), TI_CAL_U8, 2.0f, 5.0f}, \
    {"cal_can_ctr_max_jump", offsetof(ti_params_t, cal_can_ctr_max_jump), TI_CAL_U8, 1.0f, 3.0f}, \
    {"cal_bms_timeout_ms", offsetof(ti_params_t, cal_bms_timeout_ms), TI_CAL_U32, 20.0f, 500.0f}, \
    {"cal_torque_ramp_nm_s", offsetof(ti_params_t, cal_torque_ramp_nm_s), TI_CAL_F32, 200.0f, 10000.0f}, \
    {"cal_dir_change_rpm", offsetof(ti_params_t, cal_dir_change_rpm), TI_CAL_F32, 5.0f, 100.0f}, \
    {"cal_rslv_amp_min", offsetof(ti_params_t, cal_rslv_amp_min), TI_CAL_F32, 0.5f, 0.9f}, \
    {"cal_rslv_amp_max", offsetof(ti_params_t, cal_rslv_amp_max), TI_CAL_F32, 1.1f, 1.5f}, \
    {"cal_rslv_exc_min", offsetof(ti_params_t, cal_rslv_exc_min), TI_CAL_F32, 0.5f, 0.95f}, \
    {"cal_rslv_exc_max", offsetof(ti_params_t, cal_rslv_exc_max), TI_CAL_F32, 1.05f, 1.5f}, \
    {"cal_rslv_track_err_rad", offsetof(ti_params_t, cal_rslv_track_err_rad), TI_CAL_F32, 0.02f, 0.26f}, \
    {"cal_rslv_debounce", offsetof(ti_params_t, cal_rslv_debounce), TI_CAL_U8, 1.0f, 10.0f}, \
    {"cal_rslv_phase_comp_deg", offsetof(ti_params_t, cal_rslv_phase_comp_deg), TI_CAL_F32, 10.0f, 40.0f}, \
    {"cal_rslv_bw_hz", offsetof(ti_params_t, cal_rslv_bw_hz), TI_CAL_F32, 100.0f, 1000.0f}, \
    {"cal_rslv_rate_tol_frac", offsetof(ti_params_t, cal_rslv_rate_tol_frac), TI_CAL_F32, 0.05f, 0.5f}, \
    {"cal_rslv_rate_tol_rad_s", offsetof(ti_params_t, cal_rslv_rate_tol_rad_s), TI_CAL_F32, 10.0f, 200.0f}, \
    {"cal_rslv_rate_min_rad_s", offsetof(ti_params_t, cal_rslv_rate_min_rad_s), TI_CAL_F32, 50.0f, 1000.0f}, \
    {"cal_rslv_accel_max_rad_s2", offsetof(ti_params_t, cal_rslv_accel_max_rad_s2), TI_CAL_F32, 5000.0f, 200000.0f}, \
    {"cal_rslv_latency_us", offsetof(ti_params_t, cal_rslv_latency_us), TI_CAL_F32, 0.0f, 200.0f}, \
    {"cal_speed_hold_ms", offsetof(ti_params_t, cal_speed_hold_ms), TI_CAL_U32, 0.0f, 1000.0f}, \
    {"cal_rdy_timeout_ms", offsetof(ti_params_t, cal_rdy_timeout_ms), TI_CAL_U32, 250.0f, 1000.0f}, \
    {"cal_spo_release_a", offsetof(ti_params_t, cal_spo_release_a), TI_CAL_F32, 2.0f, 50.0f}, \
    {"cal_precharge_low_frac", offsetof(ti_params_t, cal_precharge_low_frac), TI_CAL_F32, 0.01f, 0.04f}, \
    {"cal_precharge_tau_min_s", offsetof(ti_params_t, cal_precharge_tau_min_s), TI_CAL_F32, 0.001f, 1.0f}, \
    {"cal_precharge_plateau_ms", offsetof(ti_params_t, cal_precharge_plateau_ms), TI_CAL_U32, 20.0f, 500.0f}, \
    {"cal_precharge_timeout_ms", offsetof(ti_params_t, cal_precharge_timeout_ms), TI_CAL_U32, 500.0f, 10000.0f}, \
    {"cal_qdis_decay_min_frac", offsetof(ti_params_t, cal_qdis_decay_min_frac), TI_CAL_F32, 0.05f, 0.25f}, \
    {"cal_qdis_stuck_on_frac", offsetof(ti_params_t, cal_qdis_stuck_on_frac), TI_CAL_F32, 0.1f, 0.5f}, \
    {"cal_fc_fraction", offsetof(ti_params_t, cal_fc_fraction), TI_CAL_F32, 0.5f, 1.0f}, \
    {"cal_mod_index_max", offsetof(ti_params_t, cal_mod_index_max), TI_CAL_F32, 0.8f, 1.0f}, \
    {"cal_dcl_kp_nm_v", offsetof(ti_params_t, cal_dcl_kp_nm_v), TI_CAL_F32, 0.05f, 5.0f}, \
    {"cal_dcl_ki_nm_vs", offsetof(ti_params_t, cal_dcl_ki_nm_vs), TI_CAL_F32, 1.0f, 200.0f}, \
    {"cal_dcl_tmax_nm", offsetof(ti_params_t, cal_dcl_tmax_nm), TI_CAL_F32, 5.0f, 200.0f}, \
    {"cal_sensor_selftest_ms", offsetof(ti_params_t, cal_sensor_selftest_ms), TI_CAL_U32, 100.0f, 2000.0f}, \
    {"cal_fs0b_release_ms", offsetof(ti_params_t, cal_fs0b_release_ms), TI_CAL_U32, 50.0f, 1000.0f}, \
    {"cal_fs26_prog_id", offsetof(ti_params_t, cal_fs26_prog_id), TI_CAL_U16, 0.0f, 65535.0f}, \
    {"cal_desat_retry_torque_frac", offsetof(ti_params_t, cal_desat_retry_torque_frac), TI_CAL_F32, 0.1f, 0.5f}, \
    {"cal_fw16_rdy_drop_ms", offsetof(ti_params_t, cal_fw16_rdy_drop_ms), TI_CAL_U32, 5.0f, 200.0f}, \
    {"cal_fw16_rdy_rise_ms", offsetof(ti_params_t, cal_fw16_rdy_rise_ms), TI_CAL_U32, 250.0f, 1000.0f}, \
    {"cal_oneshot_wait_us", offsetof(ti_params_t, cal_oneshot_wait_us), TI_CAL_U32, 260.0f, 1000.0f}, \
    {"cal_torque_max_nm", offsetof(ti_params_t, cal_torque_max_nm), TI_CAL_F32, 50.0f, 2000.0f}, \
    {"cal_desat_en_hold_us", offsetof(ti_params_t, cal_desat_en_hold_us), TI_CAL_U32, 55.0f, 250.0f}, \
    {"cal_vdyn_reserve_frac", offsetof(ti_params_t, cal_vdyn_reserve_frac), TI_CAL_F32, 0.0f, 0.2f}, \
    {"cal_vsup_ld_ms", offsetof(ti_params_t, cal_vsup_ld_ms), TI_CAL_U32, 400.0f, 1000.0f}, \
    {"cal_vsup_jump_ms", offsetof(ti_params_t, cal_vsup_jump_ms), TI_CAL_U32, 60000.0f, 120000.0f}, \
    {"cal_vsup_jump_max_v", offsetof(ti_params_t, cal_vsup_jump_max_v), TI_CAL_F32, 24.5f, 30.0f}, \
    {"cal_asc_release_ns", offsetof(ti_params_t, cal_asc_release_ns), TI_CAL_U32, 1070.0f, 5000.0f}, \
    {"cal_isns_act_min_a", offsetof(ti_params_t, cal_isns_act_min_a), TI_CAL_F32, 5.0f, 100.0f}, \
    {"cal_isns_act_frac", offsetof(ti_params_t, cal_isns_act_frac), TI_CAL_F32, 0.05f, 0.5f}, \
    {"cal_isns_act_debounce", offsetof(ti_params_t, cal_isns_act_debounce), TI_CAL_U8, 4.0f, 100.0f}, \
    {"cal_rslv_hold_us", offsetof(ti_params_t, cal_rslv_hold_us), TI_CAL_U32, 250.0f, 800.0f}, \
    {"cal_rslv_exc_target_vpp", offsetof(ti_params_t, cal_rslv_exc_target_vpp), TI_CAL_F32, 6.5f, 8.3f}, \
    {"cal_rslv_wind_per_mon", offsetof(ti_params_t, cal_rslv_wind_per_mon), TI_CAL_F32, 0.8f, 1.0f}, \
    {"cal_swg_code_init", offsetof(ti_params_t, cal_swg_code_init), TI_CAL_U8, 0.0f, 12.0f}, \
}

#define TI_CAL_RANGE_COUNT 75u

#endif /* CAL_RANGES_H */
