/* GENERATED by tools/gen-params.mjs — do not edit. Source: docs/firmware-contract.md rev A.12
 * (+ design-verify SKU data); cal_* rows: default [range] basis. */
#ifndef PARAMS_8XX_IGBT_H
#define PARAMS_8XX_IGBT_H

#define TI_PARAMS_8XX_IGBT_INIT { \
    .sku = TI_SKU_8XX_IGBT, /* FW-02 */ \
    .name = "8XX IGBT",  \
    .sic = false,  \
    .class8 = true,  \
    .vdc_min_v = 500.0f, /* §2 normal range */ \
    .vdc_max_v = 850.0f, /* §2 normal range */ \
    .ov_trip_v = 880.0f, /* §2 OV trip (both channels) */ \
    .cap_un_v = 1000.0f, /* §6 U_N at 85 degC */ \
    .c_nom_f = 0.000323f, /* 16 cans + 3 µF local */ \
    .c_min_f = 0.000291f, /* §6 C_min: -10 % + local (design-verify) */ \
    .c_max_f = 0.0003553f, /* +10 % + 3.3 µF (FW-16 energy bound) */ \
    .i_pk_rms_a = 340.0f, /* §2 peak A rms */ \
    .i_cont_rms_a = 185.0f, /* §2 continuous A rms */ \
    .i_crest_a = 480.8326f, /* √2·I_pk,rms */ \
    .i_oc_trip_a = 601.0f, /* FW-05 1.25·√2·I_pk,rms (instantaneous, both polarities) */ \
    .n_fsw = 1u, /* §2 f_sw options */ \
    .fsw_hz = {5000u, 0u}, /* §2 f_sw */ \
    .fc_ceiling_hz = {700.0f, 0.0f}, /* §2 crossover ceiling per f_sw (S6, 45 deg PM) */ \
    .dead_time_ns = 2500u, /* §2 dead time (commissioning) */ \
    .p_peak_w = 220000.0f, /* §3 peak 30 s */ \
    .p_cont_w = 120000.0f, /* §3 continuous */ \
    .hwid_r_ohm = 4700.0f, /* FW-01 RHWID */ \
    .hwid_ratio_nom = 0.3197279f, /* FW-01 V_ID 1.60 V at VREF5 = 5.0 V */ \
    .r_active_ohm = 1880.0f, /* discharge string (design-basis §4) */ \
    .r_bleed_ohm = 66000.0f, /* passive bleeder (design-basis §4) */ \
    .tau_dis_s = 0.6f, /* FW-02 / FW-18 expected τ */ \
    .qdis_2tau_s = 1.35f, /* FW-16 2τ top-up */ \
    .passive_60v_s = 65.0f, /* FW-18 passive bleeder worst case to 60 V */ \
    .s6_delay_tsw = 0.75f, /* §2: double-update PWM, sample-to-actuation 0.75 T_sw (R2-F24) */ \
    .fw03_mod_reserve = 0.95f, /* FW-03 √(3/2)·0.95·V·I·0.85 */ \
    .fw03_pf = 0.85f, /* FW-03 */ \
    .peak_time_s = 30.0f, /* §3 peak 30 s */ \
    .hwid_pullup_ohm = 10000.0f, /* FW-01 card 10 k pull-up to VREF5 */ \
    .hwid_window_frac = 0.04f, /* FW-01 ±4 % window (1 % parts) */ \
    .hwid_open_v = 4.6f, /* FW-01 open > 4.6 V */ \
    .hwid_short_v = 0.2f, /* FW-01 short < 0.2 V */ \
    .tau_band_frac = 0.2f, /* FW-02 τ > 20 % off => DTC */ \
    .qdis_on_max_ms = 5000u, /* FW-17 auto-release after 5 s */ \
    .qdis_window_ms = 300000u, /* FW-17 3 per 5 min */ \
    .qdis_max_per_window = 3u, /* FW-17 */ \
    .qdis_nodecay_ms = 200u, /* FW-18 no decay within 200 ms => stuck-off */ \
    .hv_safe_v = 60.0f, /* FW-18 / §8 < 60 V */ \
    .isns_valid_min_v = 0.2f, /* FW-05 validity window 0.2–4.8 V (HC5FW output range) */ \
    .isns_valid_max_v = 4.8f, /* FW-05 */ \
    .isns_zero_v = 2.5f, /* HC5FW 900-S: 2.5 V at 0 A (EOL cal replaces) */ \
    .isns_sens_v_per_a = 0.00222f, /* HC5FW 900-S: 2.22 mV/A at 5 V (EOL cal replaces) */ \
    .fw06_budget_us = 15.6f, /* FW-06 table: to the ASC request */ \
    .fw06_analog_us = 8.6f, /* FW-06: divider 6.2 + AMC1311B 2.1 + receiver 0.3 */ \
    .fw06_sample_hz = 200000.0f, /* FW-06: each V_DC channel free-running >= 200 kS/s */ \
    .fw06_conv_us = 1.0f, /* FW-06 conversion */ \
    .fw06_action_us = 1.0f, /* FW-06 ADC watchdog -> eFlexPWM fault -> ASC_REQ */ \
    .asc_entry_max_us = 7.5f, /* §4c hardware ASC entry <= 7.5 µs */ \
    .vdc_div_ratio = 455.8387f, /* design-basis §6: 6 x 470 k over 6.2 k into the AMC1311B */ \
    .vofs_nom_v = 0.5f, /* FW-07 receivers' shared +0.5 V offset */ \
    .vofs_min_v = 0.475f, /* FW-07 */ \
    .vofs_max_v = 0.525f, /* FW-07 */ \
    .v5gd_min_v = 4.75f, /* FW-07 / §4c V5GD 4.75–5.25 V */ \
    .v5gd_max_v = 5.25f, /* FW-07 */ \
    .v5gd_sns_ratio = 0.5f, /* card RV5GP/RV5GS 47 k/47 k: V5GD/2 */ \
    .vdc_disagree_frac = 0.05f, /* FW-07 |VDC1 - VDC2| > 5 % */ \
    .vdc_bms_frac = 0.03f, /* FW-07 |V_DC - V_pack| > 3 % with contactors closed */ \
    .vdc_failsafe_v = 0.25f, /* FW-07 channel < 0.25 V = AMC1311 fail-safe */ \
    .hvil_closed_hi_v = 3.0f, /* FW-09 signature (drive high) */ \
    .hvil_closed_lo_v = 2.0f, /* FW-09 signature (drive low) */ \
    .hvil_open_v = 2.5f, /* FW-09 signature (open = V5A/2) */ \
    .hvil_reaction_ms = 100u, /* FW-09 reaction <= 100 ms */ \
    .can_stale_ms = 20u, /* FW-11 <= 20 ms staleness */ \
    .fs26_wd_err_limit = 2u, /* FW-12 WD_ERR_LIMIT = 2 */ \
    .fs26_wdw_period_ms = 3u, /* FW-12 window <= 3 ms */ \
    .fs26_fs1b_tdelay_ms = 0u, /* FW-12 FS1B_TDELAY = 0 */ \
    .fs26_fs1b_tdur_ms = 100u, /* FW-12 FS1B_TDUR = 100 ms */ \
    .fs26_backup_fs0b = true, /* FW-12 BACKUP_SAFETY_PATH_FS0B = 1 */ \
    .fs26_backup_fs1b = false, /* FW-12 BACKUP_SAFETY_PATH_FS1B = 0 */ \
    .ntc_b_k = 3375.0f, /* §2 module NTC B25/50 3375 (both modules) */ \
    .ntc_r25_ohm = 5000.0f, /* HCS600/HCG600 DS: R25 = 5 kΩ */ \
    .ntc_pullup_ohm = 5100.0f, /* card RSN<ph>P 5.1 k to VREF5 */ \
    .ntc_series_ohm = 100.0f, /* power board R<ph>TS 100 Ω in series (ModNtc) */ \
    .bntc_b_k = 3435.0f, /* board NTC 10 k 0603, B25/85 3435 class (BOM RTAMB/RTHS) */ \
    .bntc_r25_ohm = 10000.0f, /* BOM RTAMB/RTHS */ \
    .bntc_pullup_ohm = 10000.0f, /* NtcIn RT<id>P 10 k to VREF5 */ \
    .mt_pullup_ohm = 10000.0f, /* RMT<k>P 10 k to VREF5 */ \
    .fw15_low_us = 1500u, /* FW-15 / §7 >= 1.5 ms RST/EN low */ \
    .desat_retry_min_ms = 1000u, /* FW-15 step 4: retry no sooner than 1 s */ \
    .fw16_both_below_v = 3.0f, /* FW-16 both channels below 3 V */ \
    .fw16_topup_below_v = 60.0f, /* FW-16 QDIS 2τ top-up from any reading below 60 V */ \
    .fw16_energy_max_j = 0.1f, /* FW-16 residual energy <= 0.1 J */ \
    .fw16_ss_ell_v = 12.0f, /* FW-16 n_ss: E_LL,pk(n_ss) <= 12 V */ \
    .fw16_asc_rb_us = 20u, /* FW-16 step a: ASC_CMD_RB within 20 µs */ \
    .fw16_drven_rb_us = 60u, /* FW-16 step h: DRV_EN_RB 0 within 60 µs */ \
    .asc_exit_hs_delay_ns = 1000u, /* FW-06a step 3: first HS pulse >= 1 µs after ASC_CLR */ \
    .precharge_sig_frac = 0.05f, /* FW-19 plateau ≈5 % below the pack */ \
    .cal_vdc_disagree_floor_v = 18.0f, /* CAL [5, 40] FW-07 5 % has no low-voltage floor; 2 x the ±9 V uncalibrated low-level error (R9X-07) */ \
    .cal_vdc_stale_us = 100u, /* CAL [20, 1000] free-running channel delivers a sample every <= 5 µs */ \
    .cal_vdc_bms_debounce_ms = 50u, /* CAL [10, 500] contactor/BMS transients */ \
    .cal_isum_tol_a = 45.0f, /* CAL [15, 90] Σi plausibility: 5 % of the ±900 A LEM range */ \
    .cal_isum_debounce = 3u, /* CAL [1, 10] consecutive samples */ \
    .cal_isns_offset_tol_v = 0.1f, /* CAL [0.02, 0.25] zero-current offset vs EOL cal at standstill */ \
    .cal_dtcomp_band_a = 5.0f, /* CAL [1, 30] dead-time compensation linear band */ \
    .cal_isns_stale_us = 200u, /* CAL [50, 1000] phase-current sample age limit */ \
    .cal_ntc_open_v = 4.9f, /* CAL [4.7, 4.98] pull-up to VREF5: open reads the rail */ \
    .cal_ntc_short_v = 0.1f, /* CAL [0.02, 0.3] short reads ground */ \
    .cal_temp_rate_c_s = 20.0f, /* CAL [5, 100] NTC thermal mass bounds dT/dt */ \
    .cal_tmod_derate_start_c = 90.0f, /* CAL [60, 120] FW-04 NTC derate start (thermal test T7-10 binds it) */ \
    .cal_tmod_derate_end_c = 115.0f, /* CAL [80, 140] FW-04 NTC derate to zero */ \
    .cal_derate_hyst_c = 5.0f, /* CAL [1, 15] FW-04 hysteresis */ \
    .cal_coolant_derate_start_c = 65.0f, /* CAL [50, 80] FW-04: the rated peak assumes 65 degC coolant */ \
    .cal_coolant_derate_end_c = 80.0f, /* CAL [60, 95] FW-04 */ \
    .cal_peak_recovery_s = 180.0f, /* CAL [60, 600] FW-04 'S4 time constants': 3 x the assumed 60 s plate pole */ \
    .cal_ign_on_v = 6.0f, /* CAL [4, 9] KL15 on threshold */ \
    .cal_ign_off_v = 4.0f, /* CAL [2, 6] KL15 off threshold */ \
    .cal_ign_debounce_ms = 20u, /* CAL [5, 100] KL15 debounce */ \
    .cal_hvil_tol_v = 0.2f, /* CAL [0.1, 0.24] FW-09 window half-width (signatures 0.5 V apart) */ \
    .cal_hvil_period_ms = 10u, /* CAL [5, 25] INTRLOK_P toggle period */ \
    .cal_hvil_debounce = 3u, /* CAL [2, 5] consecutive samples (3 x 10 ms + 10 ms <= 100 ms) */ \
    .cal_can_ctr_max_jump = 2u, /* CAL [1, 3] FW-11 counter: one lost frame tolerated */ \
    .cal_bms_timeout_ms = 100u, /* CAL [20, 500] FW-11 BMS-limit timeout (own timer) */ \
    .cal_torque_ramp_nm_s = 2000.0f, /* CAL [200, 10000] FW-11 ramp-to-zero rate */ \
    .cal_dir_change_rpm = 30.0f, /* CAL [5, 100] direction change only near standstill */ \
    .cal_rslv_amp_min = 0.75f, /* CAL [0.5, 0.9] FW-10 amplitude window (ratio to calibrated) */ \
    .cal_rslv_amp_max = 1.25f, /* CAL [1.1, 1.5] FW-10 */ \
    .cal_rslv_exc_min = 0.8f, /* CAL [0.5, 0.95] FW-10 excitation monitor window */ \
    .cal_rslv_exc_max = 1.2f, /* CAL [1.05, 1.5] FW-10 */ \
    .cal_rslv_track_err_rad = 0.0873f, /* CAL [0.02, 0.26] FW-10 tracking error (5 deg) */ \
    .cal_rslv_debounce = 3u, /* CAL [1, 10] FW-10 consecutive updates */ \
    .cal_rslv_phase_comp_deg = 24.0f, /* CAL [10, 40] card sin/cos input filter lags 24 deg at 10 kHz (round 13) */ \
    .cal_rslv_bw_hz = 300.0f, /* CAL [100, 1000] tracking observer bandwidth */ \
    .cal_rslv_rate_tol_frac = 0.2f, /* CAL [0.05, 0.5] FW-10 angle-rate vs current model, relative */ \
    .cal_rslv_rate_tol_rad_s = 50.0f, /* CAL [10, 200] FW-10 angle-rate vs current model, absolute (el) */ \
    .cal_rslv_rate_min_rad_s = 200.0f, /* CAL [50, 1000] back-EMF observable above this (el) */ \
    .cal_rslv_accel_max_rad_s2 = 20000.0f, /* CAL [5000, 200000] FW-10 angle-rate plausibility: driveline accel bound (el) */ \
    .cal_rslv_latency_us = 0.0f, /* CAL [0, 200] resolver chain latency beyond the mid-block reference (SDADC group delay, filter envelope delay): HIL-measured */ \
    .cal_speed_hold_ms = 200u, /* CAL [0, 1000] §6 column choice after a resolver fault: last valid speed held (inertia; FW-06 backstops a rise above n_x) */ \
    .cal_rdy_timeout_ms = 400u, /* CAL [250, 1000] FW-14: S1 73–240 ms to rails */ \
    .cal_spo_release_a = 10.0f, /* CAL [2, 50] §6 'release to SPO once the current is gone' */ \
    .cal_precharge_low_frac = 0.025f, /* CAL [0.01, 0.04] FW-19: half the 5 % signature */ \
    .cal_precharge_tau_min_s = 0.02f, /* CAL [0.001, 1] FW-19: vehicle R_pre·C_min (commissioning) */ \
    .cal_precharge_plateau_ms = 100u, /* CAL [20, 500] FW-19 plateau detection window */ \
    .cal_precharge_timeout_ms = 3000u, /* CAL [500, 10000] FW-19 */ \
    .cal_qdis_decay_min_frac = 0.1f, /* CAL [0.05, 0.25] FW-18: minimum drop in 200 ms (τ 0.6 s gives 28 %) */ \
    .cal_qdis_stuck_on_frac = 0.25f, /* CAL [0.1, 0.5] stuck-ON: QDIS off but τ below this fraction of the bleeder τ */ \
    .cal_fc_fraction = 0.9f, /* CAL [0.5, 1] current-loop crossover as a fraction of the §2 ceiling */ \
    .cal_mod_index_max = 0.95f, /* CAL [0.8, 1] 5 % modulation reserve (FW-03) */ \
    .cal_dcl_kp_nm_v = 0.5f, /* CAL [0.05, 5] FW-08 DC-link voltage controller */ \
    .cal_dcl_ki_nm_vs = 20.0f, /* CAL [1, 200] FW-08 */ \
    .cal_dcl_tmax_nm = 50.0f, /* CAL [5, 200] FW-08 torque authority */ \
    .cal_sensor_selftest_ms = 500u, /* CAL [100, 2000] §9 step 3 timeout */ \
    .cal_fs0b_release_ms = 200u, /* CAL [50, 1000] §9 step 4: the FS26 needs WD_RFR_LIMIT good refreshes first */ \
    .cal_fs26_prog_id = 65535u, /* CAL [0, 65535] FW-12: M_PROGID of the procured OTP variant; 0xFFFF = unbound (no arming) */ \
    .cal_desat_retry_torque_frac = 0.3f, /* CAL [0.1, 0.5] FW-15 step 4 'at reduced torque' */ \
    .cal_fw16_rdy_drop_ms = 50u, /* CAL [5, 200] FW-16 d/e RDY drop timeout */ \
    .cal_fw16_rdy_rise_ms = 300u, /* CAL [250, 1000] FW-16 d/e RDY rise timeout (S1 240 ms) */ \
    .cal_oneshot_wait_us = 300u, /* CAL [260, 1000] §7: one-shot 72–210 µs + DRV_EN RC 16–46 µs */ \
    .cal_torque_max_nm = 450.0f, /* CAL [50, 2000] motor torque limit (commissioning) */ \
    .cal_desat_en_hold_us = 60u, /* CAL [55, 250] A12-R05: no software MCU_GATE_EN drop within this time of a FLT (latch path 22–53 µs + margin) */ \
    .cal_vdyn_reserve_frac = 0.05f, /* CAL [0, 0.2] F23: voltage kept free for current-loop dynamics (torque->current feasibility) */ \
    .cal_isns_act_min_a = 20.0f, /* CAL [5, 100] F24: a phase whose reference reaches this must show current */ \
    .cal_isns_act_frac = 0.2f, /* CAL [0.05, 0.5] F24: measured phase current vs its reference (stuck channel below) */ \
    .cal_isns_act_debounce = 20u, /* CAL [4, 100] F24: consecutive applicable samples below the fraction => stuck channel */ \
}

#endif /* PARAMS_8XX_IGBT_H */
