/* dtc_table.h — GENERATED by tools/dtc-table.mjs from src/comms/dtc.h (FW-40): do not edit. After any change of the
 * DTC list run `node tools/dtc-table.mjs --c`; until then the unit test uds_diag: every_dtc_has_a_number_and_a_description
 * fails. One row per DTC, keyed by its enumerator: the UDS DTC number (dtc_code(): 0xD10000 | id, ISO 14229-1 DTC
 * format 0x01) and the service tool's description — the table `node tools/dtc-table.mjs` prints as JSON. Test-only:
 * the image carries the numbers (dtc_code), not the texts. */
#ifndef DTC_TABLE_H
#define DTC_TABLE_H

#include "dtc.h"

typedef struct {
    const char *name;
    uint32_t number;
    const char *text;
} dtc_table_row_t;

#define DTC_TABLE_N 81u /* DTC_COUNT when generated */

static const dtc_table_row_t DTC_TABLE[DTC_COUNT] = {
    [DTC_FS26_PROGID] = {"DTC_FS26_PROGID", 0xD10001u, "Safety SBC (FS26) OTP variant: M_PROGID unbound or not the procured one - no arming (FW-12)"},
    [DTC_FS26_OTP_CORRUPT] = {"DTC_FS26_OTP_CORRUPT", 0xD10002u, "Safety SBC (FS26) OTP CRC monitor reports corruption - no arming (FW-12)"},
    [DTC_FS26_DEBUG_MODE] = {"DTC_FS26_DEBUG_MODE", 0xD10003u, "Safety SBC (FS26) in debug mode at boot - no arming (FW-12)"},
    [DTC_FS26_INIT_READBACK] = {"DTC_FS26_INIT_READBACK", 0xD10004u, "Safety SBC (FS26) INIT registers or their complements read back wrong - no arming (FW-12)"},
    [DTC_FS26_SPI] = {"DTC_FS26_SPI", 0xD10005u, "Safety SBC (FS26) SPI communication failed at boot - no arming (FW-12)"},
    [DTC_FS26_WD] = {"DTC_FS26_WD", 0xD10006u, "Safety SBC (FS26) watchdog answer refused or not sent (FW-12)"},
    [DTC_FS26_RELEASE] = {"DTC_FS26_RELEASE", 0xD10007u, "Safety SBC (FS26) did not release FS0B/FS1B - no arming (start-up step 4)"},
    [DTC_FS1B_SHORT_HIGH] = {"DTC_FS1B_SHORT_HIGH", 0xD10008u, "FS1B / FAULT_OUT line shorted to KL30 - no arming until repaired"},
    [DTC_FS26_GPIO1_OTP] = {"DTC_FS26_GPIO1_OTP", 0xD10009u, "Gate power up before start-up step 6: FS_GPIO1 slotted in the FS26 OTP - no arming"},
    [DTC_HWID_OPEN] = {"DTC_HWID_OPEN", 0xD1000Au, "HW_ID input open (power-board identity resistor missing) - no arming (FW-01)"},
    [DTC_HWID_SHORT] = {"DTC_HWID_SHORT", 0xD1000Bu, "HW_ID input shorted to ground - no arming (FW-01)"},
    [DTC_HWID_UNKNOWN] = {"DTC_HWID_UNKNOWN", 0xD1000Cu, "HW_ID reading outside every SKU window or unstable - no arming (FW-01)"},
    [DTC_SKU_MISMATCH] = {"DTC_SKU_MISMATCH", 0xD1000Du, "HW_ID, parameter set and calibration record disagree on the SKU - no gate enable (FW-02)"},
    [DTC_CALIB_INVALID] = {"DTC_CALIB_INVALID", 0xD1000Eu, "Calibration record missing or wrong (layout, CRC, range, SKU, serial, motor ID) - no torque (FW-20)"},
    [DTC_PARAMS_INVALID] = {"DTC_PARAMS_INVALID", 0xD1000Fu, "Parameter set fails its range or consistency check - no arming"},
    [DTC_PWM_LOCK] = {"DTC_PWM_LOCK", 0xD10010u, "PWM fault configuration not read back, or its register lock not set - no arming (FW-24)"},
    [DTC_DESAT_HS] = {"DTC_DESAT_HS", 0xD10011u, "High-side gate driver desaturation (short circuit) (FW-15)"},
    [DTC_DESAT_LS] = {"DTC_DESAT_LS", 0xD10012u, "Low-side gate driver desaturation (short circuit) (FW-15)"},
    [DTC_DESAT_REPEAT] = {"DTC_DESAT_REPEAT", 0xD10013u, "Second desaturation in the key cycle - latched, no further retry (FW-15)"},
    [DTC_DESAT_PENDING_BOOT] = {"DTC_DESAT_PENDING_BOOT", 0xD10014u, "Gate driver fault line low at boot: a desaturation from before the reset"},
    [DTC_FLT_RECOVERY_FAIL] = {"DTC_FLT_RECOVERY_FAIL", 0xD10015u, "Gate driver fault latch not reset by the FW-15 recovery sequence"},
    [DTC_OVERCURRENT] = {"DTC_OVERCURRENT", 0xD10016u, "Phase overcurrent: hardware compare or software backstop, outside the ASC-entry window (FW-05)"},
    [DTC_OVERVOLTAGE] = {"DTC_OVERVOLTAGE", 0xD10017u, "DC-link overvoltage: hardware compare, active short circuit requested (FW-06)"},
    [DTC_ISNS_OPEN] = {"DTC_ISNS_OPEN", 0xD10018u, "Phase current sensor output open (below its valid window) (FW-05)"},
    [DTC_ISNS_RANGE] = {"DTC_ISNS_RANGE", 0xD10019u, "Phase current sensor output outside its valid window (FW-05)"},
    [DTC_ISNS_SUM] = {"DTC_ISNS_SUM", 0xD1001Au, "Phase currents do not sum to zero (FW-05)"},
    [DTC_ISNS_OFFSET] = {"DTC_ISNS_OFFSET", 0xD1001Bu, "Phase current zero-current offset outside its tolerance at key-on"},
    [DTC_ISNS_STALE] = {"DTC_ISNS_STALE", 0xD1001Cu, "Phase current samples missing or stale: lost triplets or a stopped current loop (FW-27, FW-31)"},
    [DTC_VDC_DISAGREE] = {"DTC_VDC_DISAGREE", 0xD1001Du, "DC-link voltage channels disagree beyond 5 % (FW-07)"},
    [DTC_VOFS] = {"DTC_VOFS", 0xD1001Eu, "DC-link sense offset reference (VOFS) out of range (FW-07)"},
    [DTC_V5GD] = {"DTC_V5GD", 0xD1001Fu, "Gate-drive side 5 V supply (V5GD) out of range - pulses off, short circuit cleared"},
    [DTC_VDC_FAILSAFE] = {"DTC_VDC_FAILSAFE", 0xD10020u, "DC-link voltage channel in its isolated amplifier's fail-safe state (FW-07)"},
    [DTC_VDC_STALE] = {"DTC_VDC_STALE", 0xD10021u, "DC-link voltage samples stale (FW-07)"},
    [DTC_VDC_BMS] = {"DTC_VDC_BMS", 0xD10022u, "DC-link voltage leaving the BMS pack voltage with the contactors closed (battery path)"},
    [DTC_RSLV_AMPLITUDE] = {"DTC_RSLV_AMPLITUDE", 0xD10023u, "Resolver sin/cos amplitude outside its window (FW-10)"},
    [DTC_RSLV_EXCITATION] = {"DTC_RSLV_EXCITATION", 0xD10024u, "Resolver excitation outside its band at the monitor or the winding (FW-10, FW-30)"},
    [DTC_RSLV_TRACKING] = {"DTC_RSLV_TRACKING", 0xD10025u, "Resolver tracking error above its limit (FW-10)"},
    [DTC_RSLV_ACCEL] = {"DTC_RSLV_ACCEL", 0xD10026u, "Resolver acceleration implausible (FW-10)"},
    [DTC_RSLV_RATE] = {"DTC_RSLV_RATE", 0xD10027u, "Resolver angle rate disagrees with the voltage-model speed (FW-10)"},
    [DTC_TEMP_MODULE] = {"DTC_TEMP_MODULE", 0xD10028u, "Power-module temperature sensor invalid: open, short or rate (FW-13)"},
    [DTC_TEMP_BOARD] = {"DTC_TEMP_BOARD", 0xD10029u, "Board temperature sensor invalid (FW-13)"},
    [DTC_TEMP_MOTOR] = {"DTC_TEMP_MOTOR", 0xD1002Au, "Motor temperature sensor invalid (FW-13)"},
    [DTC_OVERTEMP] = {"DTC_OVERTEMP", 0xD1002Bu, "Hottest module temperature at the end of its derating band - no torque left (FW-04, FW-13)"},
    [DTC_HVIL_OPEN] = {"DTC_HVIL_OPEN", 0xD1002Cu, "HVIL loop open (FW-09)"},
    [DTC_HVIL_SHORT] = {"DTC_HVIL_SHORT", 0xD1002Du, "HVIL loop shorted to ground or a supply, or implausible (FW-09)"},
    [DTC_CAN_TIMEOUT] = {"DTC_CAN_TIMEOUT", 0xD1002Eu, "Vehicle command (VCU_CMD) missing or older than 20 ms (FW-11)"},
    [DTC_BMS_TIMEOUT] = {"DTC_BMS_TIMEOUT", 0xD1002Fu, "BMS limits (VCU_BMS) missing or stale - no regeneration (FW-11)"},
    [DTC_CAN_E2E] = {"DTC_CAN_E2E", 0xD10030u, "Vehicle CAN frame refused by its E2E check: CRC, alive counter or length (FW-11)"},
    [DTC_QDIS_STUCK_OFF] = {"DTC_QDIS_STUCK_OFF", 0xD10031u, "Active discharge commanded but the link does not discharge (FW-17, FW-18)"},
    [DTC_QDIS_STUCK_ON] = {"DTC_QDIS_STUCK_ON", 0xD10032u, "Active discharge conducting without a command - service lock, do not re-energise (FW-26)"},
    [DTC_QDIS_RATE_LIMIT] = {"DTC_QDIS_RATE_LIMIT", 0xD10033u, "Active discharge requests beyond the rate limit (FW-17)"},
    [DTC_TAU_MISMATCH] = {"DTC_TAU_MISMATCH", 0xD10034u, "Key-off discharge time constant more than 20 % off the SKU's capacitor bank (FW-02)"},
    [DTC_PRECHARGE_PLATEAU] = {"DTC_PRECHARGE_PLATEAU", 0xD10035u, "Precharge plateau below 97.5 % of the pack - arming refused (FW-19)"},
    [DTC_PRECHARGE_TAU] = {"DTC_PRECHARGE_TAU", 0xD10036u, "Precharge time constant implausible - arming refused (FW-19)"},
    [DTC_PRECHARGE_TIMEOUT] = {"DTC_PRECHARGE_TIMEOUT", 0xD10037u, "Precharge not complete in time - arming refused (FW-19)"},
    [DTC_SELFTEST_FAIL] = {"DTC_SELFTEST_FAIL", 0xD10038u, "Gate shutdown-path self-test step mismatch - no arming (FW-16)"},
    [DTC_SELFTEST_NO_PASS] = {"DTC_SELFTEST_NO_PASS", 0xD10039u, "Gate self-test skipped with no stored pass - no arming (FW-16)"},
    [DTC_GATE_POWER] = {"DTC_GATE_POWER", 0xD1003Au, "Gate-drive supply not ready in time, or lost (RDY) (FW-14)"},
    [DTC_SPO_ENERGY] = {"DTC_SPO_ENERGY", 0xD1003Bu, "Pulses held off with neither energy rule proven: no safe state proven (FW-08b)"},
    [DTC_CTRL_NONFINITE] = {"DTC_CTRL_NONFINITE", 0xD1003Cu, "Non-finite value caught in the control path before the PWM"},
    [DTC_NVM] = {"DTC_NVM", 0xD1003Du, "Data-flash (NVM) write failed"},
    [DTC_SENSOR_SELFTEST] = {"DTC_SENSOR_SELFTEST", 0xD1003Eu, "Sensor self-test at start-up failed (start-up step 3)"},
    [DTC_GAINS] = {"DTC_GAINS", 0xD1003Fu, "No current-loop gain set within the crossover ceiling - no arming"},
    [DTC_ARM_EVIDENCE] = {"DTC_ARM_EVIDENCE", 0xD10040u, "Arming evidence missing: fault route unbound or no valid EOL/HIL validation record - no arming (FW-24)"},
    [DTC_TORQUE_INFEASIBLE] = {"DTC_TORQUE_INFEASIBLE", 0xD10041u, "No voltage-feasible current even at zero torque: zero torque, speed limit requested (FW-25, FW-37)"},
    [DTC_ISNS_STUCK] = {"DTC_ISNS_STUCK", 0xD10042u, "Phase current channel shows no current where its reference asks for it: stuck sensor (FW-05)"},
    [DTC_RSLV_STALE] = {"DTC_RSLV_STALE", 0xD10043u, "No coherent resolver frame within the hold time - angle withdrawn (FW-28)"},
    [DTC_RSLV_SWG_SAT] = {"DTC_RSLV_SWG_SAT", 0xD10044u, "Resolver excitation trim at its top code with the monitor still below the setpoint (FW-30)"},
    [DTC_SERVICE_LOCK_CLEARED] = {"DTC_SERVICE_LOCK_CLEARED", 0xD10045u, "Service lock cleared by the UDS routine 0xF010 - a record, not a failure (FW-32)"},
    [DTC_LV_OVERVOLTAGE] = {"DTC_LV_OVERVOLTAGE", 0xD10046u, "LV supply (VSUP) above 20 V - information; first and last time give the duration (FW-33)"},
    [DTC_LV_OV_SUSTAINED] = {"DTC_LV_OV_SUSTAINED", 0xD10047u, "LV overvoltage longer than its band allows - orderly ramp to zero torque (FW-33)"},
    [DTC_LV_VSUP_UNKNOWN] = {"DTC_LV_VSUP_UNKNOWN", 0xD10048u, "No LV supply reading from the FS26 AMUX - LV supervision off (information, FW-33)"},
    [DTC_RSLV_REACQUIRED] = {"DTC_RSLV_REACQUIRED", 0xD10049u, "Resolver frame ring re-acquired, or its producer restarted - information (FW-35)"},
    [DTC_TORQUE_POSTCOND] = {"DTC_TORQUE_POSTCOND", 0xD1004Au, "Torque-to-current solver refused its own result: no current reference, control lost (FW-37)"},
    [DTC_OVERSPEED] = {"DTC_OVERSPEED", 0xD1004Bu, "Measured speed in the overspeed warning or trip band (FW-42)"},
    [DTC_FW_UPDATE] = {"DTC_FW_UPDATE", 0xD1004Cu, "Programming session entered (firmware update) - no arming until the next power-up; a record (FW-38)"},
    [DTC_FW_FALLBACK] = {"DTC_FW_FALLBACK", 0xD1004Du, "Bootloader refused or abandoned the last activation, or restored the last good image (FW-38)"},
    [DTC_MC_ABORTED] = {"DTC_MC_ABORTED", 0xD1004Eu, "Commissioning routine aborted - its reason is in the routine's results; a record (FW-39)"},
    [DTC_MC_CAL_WRITTEN] = {"DTC_MC_CAL_WRITTEN", 0xD1004Fu, "Commissioning wrote a new calibration record version - effective at the next key cycle (FW-39)"},
    [DTC_ASC_OC_TRANSIENT] = {"DTC_ASC_OC_TRANSIENT", 0xD10050u, "Phase overcurrent inside the ASC-entry window: the short-circuit transient - information (FW-05)"},
};

#endif /* DTC_TABLE_H */
